/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pratikum29062026;

/**
 *
 * @author usert
 */
public class FromMinuman extends javax.swing.JFrame {

    /**
     * Creates new form FromMinuman
     */
    
    private FromUtama utama;
    
    public FromMinuman() {
        initComponents();
    }

    public FromMinuman(FromUtama utama) {
        this.utama = utama;
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ckbjoz = new javax.swing.JCheckBox();
        txtTotal = new javax.swing.JTextField();
        ckbteh = new javax.swing.JCheckBox();
        btnKembali = new javax.swing.JButton();
        txtjuk = new javax.swing.JTextField();
        btnTotal = new javax.swing.JButton();
        txtjoz = new javax.swing.JTextField();
        txtteh = new javax.swing.JTextField();
        cbjuk = new javax.swing.JComboBox<>();
        cbjoz = new javax.swing.JComboBox<>();
        cbteh = new javax.swing.JComboBox<>();
        txtTotaljuk = new javax.swing.JTextField();
        txtTotaljoz = new javax.swing.JTextField();
        txtTotalteh = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        ckbjuk = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ckbjoz.setText("ekstra joz");
        ckbjoz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckbjozActionPerformed(evt);
            }
        });

        txtTotal.setText("0");
        txtTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalActionPerformed(evt);
            }
        });

        ckbteh.setText("teh es");
        ckbteh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckbtehActionPerformed(evt);
            }
        });

        btnKembali.setText("Kembali");
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });

        txtjuk.setText("0");
        txtjuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtjukActionPerformed(evt);
            }
        });

        btnTotal.setText("Total");
        btnTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTotalActionPerformed(evt);
            }
        });

        txtjoz.setText("0");
        txtjoz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtjozActionPerformed(evt);
            }
        });

        txtteh.setText("0");
        txtteh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttehActionPerformed(evt);
            }
        });

        cbjuk.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jumlah", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        cbjuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbjukActionPerformed(evt);
            }
        });

        cbjoz.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jumlah", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        cbjoz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbjozActionPerformed(evt);
            }
        });

        cbteh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jumlah", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        cbteh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbtehActionPerformed(evt);
            }
        });

        txtTotaljuk.setText("0");

        txtTotaljoz.setText("0");
        txtTotaljoz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotaljozActionPerformed(evt);
            }
        });

        txtTotalteh.setText("0");
        txtTotalteh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotaltehActionPerformed(evt);
            }
        });

        jLabel1.setText("MENU MINUMAN");

        ckbjuk.setText("Juk Jerus");
        ckbjuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckbjukActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ckbjuk, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(ckbteh, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ckbjoz, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtjoz, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cbjoz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtTotaljoz))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtteh, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cbteh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtTotalteh))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtjuk, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cbjuk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtTotaljuk, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(86, 86, 86)
                                .addComponent(btnTotal)
                                .addGap(18, 18, 18)
                                .addComponent(txtTotal))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(btnKembali)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ckbjuk)
                    .addComponent(txtjuk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbjuk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotaljuk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ckbjoz)
                    .addComponent(txtjoz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbjoz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotaljoz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ckbteh)
                    .addComponent(txtteh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbteh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotalteh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTotal))
                .addGap(34, 34, 34)
                .addComponent(btnKembali)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ckbjozActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckbjozActionPerformed
        txtjoz.setText("12000");
    }//GEN-LAST:event_ckbjozActionPerformed

    private void txtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalActionPerformed

    private void ckbtehActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckbtehActionPerformed
        txtteh.setText("10000");
    }//GEN-LAST:event_ckbtehActionPerformed

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        String total = txtTotal.getText();
        utama.setTotalMinuman(total);
        this.dispose();
    }//GEN-LAST:event_btnKembaliActionPerformed

    private void txtjukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtjukActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtjukActionPerformed

    private void btnTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTotalActionPerformed
        double a = Double.parseDouble(txtTotaljuk.getText());
        double b = Double.parseDouble(txtTotaljoz.getText());
        double c = Double.parseDouble(txtTotalteh.getText());
        double total = a+b+c;
        txtTotal.setText(Double.toString(total));
    }//GEN-LAST:event_btnTotalActionPerformed

    private void txtjozActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtjozActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtjozActionPerformed

    private void txttehActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttehActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttehActionPerformed

    private void cbjukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbjukActionPerformed
        int jumlah = (int)cbjuk.getSelectedIndex();
        double harga = Double.parseDouble(txtjuk.getText());
        double total = jumlah * harga;
        txtTotaljuk.setText(Double.toString(total));

    }//GEN-LAST:event_cbjukActionPerformed

    private void cbjozActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbjozActionPerformed
        int jumlah = (int)cbjoz.getSelectedIndex();
        double harga = Double.parseDouble(txtjoz.getText());
        double total = jumlah * harga;
        txtTotaljoz.setText(Double.toString(total));
    }//GEN-LAST:event_cbjozActionPerformed

    private void cbtehActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbtehActionPerformed
        int jumlah = (int)cbteh.getSelectedIndex();
        double harga = Double.parseDouble(txtteh.getText());
        double total = jumlah * harga;
        txtTotalteh.setText(Double.toString(total));
    }//GEN-LAST:event_cbtehActionPerformed

    private void txtTotaljozActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotaljozActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotaljozActionPerformed

    private void txtTotaltehActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotaltehActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotaltehActionPerformed

    private void ckbjukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckbjukActionPerformed
        txtjuk.setText("15000");
    }//GEN-LAST:event_ckbjukActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FromMinuman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FromMinuman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FromMinuman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FromMinuman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FromMinuman().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnTotal;
    private javax.swing.JComboBox<String> cbjoz;
    private javax.swing.JComboBox<String> cbjuk;
    private javax.swing.JComboBox<String> cbteh;
    private javax.swing.JCheckBox ckbjoz;
    private javax.swing.JCheckBox ckbjuk;
    private javax.swing.JCheckBox ckbteh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JTextField txtTotaljoz;
    private javax.swing.JTextField txtTotaljuk;
    private javax.swing.JTextField txtTotalteh;
    private javax.swing.JTextField txtjoz;
    private javax.swing.JTextField txtjuk;
    private javax.swing.JTextField txtteh;
    // End of variables declaration//GEN-END:variables
}
